### ISSUE TITLE
App Parameters

### ISSUE THREAD

**Issue by Jrofalk** [asanderson09/Project1#2]
#User Story 1
As a electric car owner, I want to be able to locate charging stations, so that I can charge my car.

#Task #1 - Create the overall layout of the webpage

#Acceptance Criteria
- [x] Create header
- [x] Create drop down menu
- [x] Create map view section
- [x] Create wiki display
- [ ] Create footer that includes copyright

**Comment by Jrofalk** [comment]
The only thing above that is missing is the copyright tag. However, there is a footer. This is a relatively minor issue.
